<div class="sidebarR">
<h3>Forums</h3>
	<ul>
		<li><a href="http://www.lifeaftermormonism.net/">Life After Mormonism</a></li>
		<li><a href="http://mormondiscussions.com/phpBB3/">Mormon Discussions</a></li>
		<li><a href="http://forum.newordermormon.org/">New Order Mormon</a></li>
		<li><a href="http://www.postmormon.org/exp_e/index.php/home/">PostMormon.org</a></li>
		<li><a href="http://www.reddit.com/r/exmormon/">Reddit Ex-mormons</a></li>
	</ul>
<br />
<h3>Podcasts</h3>
	<ul>
		<li><a href="http://athoughtfulfaith.org/">A Thoughtful Faith</a></li>
	        <li><a href="http://www.iamanexmormon.com/">I Am An Ex Mormon</a></li>
		<li><a href="http://infantsonthrones.com/">Infants on Thrones</a></li>
		<li><a href="http://www.irreligiosophy.com/">Irreligiosophy</a></li>
		<li><a href="http://mybookofmormonpodcast.com/">My Book of Mormon</a></li>
		<li><a href="http://mormonexpositor.com/">Mormon Expositor</a></li>
		<li><a href="http://mormonmatters.org/">Mormon Matters</a></li>
		<li><a href="http://mormonstories.org/">Mormon Stories</a></li>
		<li><a href="http://www.mormontransitions.org/category/podcast/">Mormon Transitions Podcast</a></li>
		<li><a href="http://nakedmormonismpodcast.com/index.html">Naked Mormonism Podcast</a></li>
		<li><a href="https://elderwrongshow.podbean.com/">The drunk Mormon Missionary Podcast</a></li>
	</ul>
<br />
<h3>Awards</h3>
  <ul>
          <li><a href="http://mainstreetplaza.com/2017/02/03/congratulations-2016-brodie-award-winners/">2016 Brodies</a></li>
                          <li><a href="http://mainstreetplaza.com/2017/01/12/congratulations-to-x-mormon-of-the-year-2016-jeremy-runnells/">2016 Wm. Law X-Mo of the Year</a></li>
          <li><a href="https://mainstreetplaza.com/2016/02/06/congratulations-brodie-award-winners-2015/">2015 Brodies</a></li>
                          <li><a href="http://mainstreetplaza.com/2016/01/22/congratulations-2015-x-mormon-of-the-year-john-dehlin/">2015 Wm. Law X-Mo of the Year</a></li>
          <li><a href="http://mainstreetplaza.com/2015/02/12/congratulations-2014-brodie-award-winners/">2014 Brodies</a></li>
                          <li><a href="http://mainstreetplaza.com/2015/01/22/congratulations-to-x-mormon-of-the-year-2014-kate-kelly/">2014 Wm. Law X-Mo of the Year</a></li>
          <li><a href="http://mainstreetplaza.com/2014/02/12/congratulations-2013-brodie-award-winners/">2013 Brodies</a></li>
                          <li><a href="http://mainstreetplaza.com/2014/01/23/congratulations-to-2013-x-mormons-of-the-year-j-seth-anderson-and-michael-ferguson/">2013 Wm. Law X-Mo of the Year</a></li>
	  <li><a href="http://mainstreetplaza.com/2013/02/06/congratulations-2012-brodie-winners/">2012 Brodies</a></li>
		<li><a href="http://mainstreetplaza.com/2013/01/16/congratulations-to-wm-law-x-mormon-of-the-year-2012-david-twede/">2012 Wm. Law X-Mo of the Year</a></li>
	  <li><a href="http://mainstreetplaza.com/2012/02/16/congratulations-2011-brodie-winners/">2011 Brodies</a></li>
		<li><a href="http://mainstreetplaza.com/2012/03/22/congratulations-2011-x-mormon-of-the-year-joanna-brooks/">2011 Wm. Law X-Mo of the Year</a></li>
	  <li><a href="http://mainstreetplaza.com/2011/01/23/congratulations-2010-brodie-winners/">2010 Brodies</a></li>
		<li><a href="http://mainstreetplaza.com/2011/02/13/congratulations-william-law-x-mormon-year-2010-monica-bielanko/">2010 Wm. Law X-Mo of the Year</a></li>
		<li><a href="http://mainstreetplaza.com/2010/02/23/the-2009-brodie-winners-are/">2009 Brodies</a></li>
		<li><a href="http://mainstreetplaza.com/2010/02/02/the-2009-william-law-x-mormon-of-the-year-walter-kirn/">2009 Wm. Law X-Mo of the Year</a></li>
  </ul>
<br />
<h3>Meta</h3>
  <ul>
	  <li><a href="http://outerblogness.org/about.php">About Us</a></li>
		<li><a href="http://outerblogness.org/about.php#participate">List Your Blog</a></li>
  </ul><br />
</div> <!-- end sidebarR -->
